services:
  mariadb:
    image: mariadb:latest
    command: ["--bind-address=0.0.0.0"]
    environment:
      MARIADB_ROOT_PASSWORD: "123"
      MARIADB_DATABASE: dashboard_demo
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping --protocol=tcp -h 127.0.0.1 -uroot -p$${MARIADB_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: app_backend
    ports:
      - "5001:5001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/dashboard_demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "123"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge